CREATE TABLE IF NOT EXISTS spans (
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL PRIMARY KEY,
    parent_span_id TEXT,
    run_id TEXT NOT NULL,
    session_id TEXT,
    user_id_hash TEXT,
    span_kind TEXT NOT NULL,
    name TEXT NOT NULL,
    start_time INTEGER NOT NULL,
    end_time INTEGER,
    status TEXT NOT NULL,
    status_message TEXT,
    error_type TEXT,
    error_message_redacted TEXT,
    attributes TEXT NOT NULL,
    otel_attributes TEXT NOT NULL,
    openinference_attributes TEXT NOT NULL,
    memory_state TEXT,
    input_ref TEXT,
    output_ref TEXT,
    prompt_template_id TEXT,
    prompt_version TEXT,
    model_provider TEXT,
    model_name TEXT,
    tool_name TEXT,
    tool_schema_hash TEXT,
    retrieval_query_hash TEXT,
    retrieved_document_refs TEXT NOT NULL,
    token_usage TEXT,
    cost_estimate TEXT,
    latency_ms INTEGER,
    retry_count INTEGER,
    cache_hit BOOLEAN,
    redaction_policy TEXT NOT NULL,
    schema_version TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_spans_trace_id ON spans(trace_id);
CREATE INDEX IF NOT EXISTS idx_spans_run_id ON spans(run_id);
